[project]
name = "xloracustomnode"
description = "Custom Multi-LoRA node for ComfyUI with generic triggers and dynamic UI"
version = "1.0.0"

[project.urls]
Repository = "https://github.com/xd43vild69/xLoraCustomNode"

[tool.comfy]
PublisherId = "xd43vild69"
DisplayName = "xLoraCustomNode"
includes = ["js/*", "nodes/*", "__init__.py"]

